In [38]:
import pandas as pd
from sklearn.model_selection import train_test_split
import numpy as np

In [39]:
df = pd.read_csv("spam.csv")
df.head(3)

Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...

In [40]:
df.groupby("Category").describe()

Message                                                            \
           count unique                                                top   
Category                                                                     
ham         4825   4516                             Sorry, I'll call later   
spam         747    641  Please call our customer service representativ...   

               
         freq  
Category       
ham        30  
spam        4

In [41]:
df["spam"] = df.Category.apply(lambda x: 1 if x == "spam" else 0)
df = df.drop(columns = ["Category"], axis = 1)
df.head(3)

Message  spam
0  Go until jurong point, crazy.. Available only ...     0
1                      Ok lar... Joking wif u oni...     0
2  Free entry in 2 a wkly comp to win FA Cup fina...     1

In [42]:
X_train, X_test, y_train, y_test = train_test_split(df.Message, df.spam, test_size = 0.2)

In [43]:
from sklearn.feature_extraction.text import CountVectorizer
vectorizer = CountVectorizer()
X_train_count = vectorizer.fit_transform(X_train.values)
X_train_count.toarray()[:3]

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [50]:
from sklearn.naive_bayes import MultinomialNB
model = MultinomialNB()
model.fit(X_train_count, y_train)

MultinomialNB()

In [51]:
from sklearn.model_selection import cross_val_score
cross_val_score(model, X_train_count, y_train)

array([0.9809417 , 0.98318386, 0.97755331, 0.97867565, 0.97306397])

In [52]:
X_test_count = vectorizer.transform(X_test.values)

model.score(X_test_count, y_test)

0.9874439461883409

In [53]:
emails = [
    "Hey mohan, can we get together to watch football game tomorrow?",
    "Upto 20% discount on parking, exclusive offer just for you. Dont miss on the reward!"
]
emails_count = vectorizer.transform(emails)
model.predict(emails_count)

array([0, 1], dtype=int64)

In [55]:
from sklearn.pipeline import Pipeline
clf = Pipeline([
    ("vectorizer", CountVectorizer()),
    ("nb", MultinomialNB())
])
clf.fit(X_train, y_train)

Pipeline(steps=[('vectorizer', CountVectorizer()), ('nb', MultinomialNB())])

In [56]:
clf.score(X_test, y_test)

0.9874439461883409

In [57]:
clf.predict(emails)

array([0, 1], dtype=int64)