In [8]:
import numpy as np

In [19]:
revenue = np.array([[180, 200, 220], [24, 36, 40], [12, 18, 20]])
expense = np.array([[80, 90, 100], [10, 16, 20], [8, 10, 10]])
profit  = revenue - expense

In [20]:
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [21]:
pricePerUnit = np.array([1000, 400, 1200])
units = np.array([[30, 40, 50], [5, 10, 15], [2, 5, 7]])
#for each individual company - type casting
x = pricePerUnit * units
#for combined brands - dot product
y = np.dot(pricePerUnit, units)

x, y

(array([[30000, 16000, 60000],
        [ 5000,  4000, 18000],
        [ 2000,  2000,  8400]]),
 array([34400, 50000, 64400]))

In [27]:
#usd - rupee conversion

#revenue in usd
revenue_usd = np.array([[200, 220, 250], [68, 79, 105], [110, 140, 180], [80, 85, 90]]) * 1000000
#revenue in ruppees
revenue_rpe = revenue_usd * 75

#dot function
total_revenue_per_year = np.dot(revenue_usd, np.array([75, 75, 75]))
#sum function
total_revenue_per_year_rupee = np.sum(revenue_rpe, axis = 1)

total_revenue_per_year_rupee, total_revenue_per_year

(array([-1289607552,  1720130816, -2109738368,  1945130816]),
 array([-1289607552,  1720130816, -2109738368,  1945130816]))